modLoader = "javafml"
loaderVersion = "[49,)"
license = "All Rights Reserved"

[[mods]]
modId = "identity2"
version = "${version}"
displayName = "Identity2"
authors = "Gabou"
description = '''

'''

[[dependencies.identity2]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.identity2]]
modId = "gaboulibs"
mandatory = true
versionRange = "[1.4,)"
ordering = "AFTER"
side = "BOTH"
