modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "identity2"
version = "${version}"
displayName = "Identity2"
authors = "Gabou"
description = '''

'''

[[dependencies.identity2]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.identity2]]
modId = "gaboulibs"
mandatory = true
versionRange = "[1.9,)"
ordering = "AFTER"
side = "BOTH"
