sourceSets {
    main {
        java {
            exclude 'net/Gabou/identity2/mixin/PlayerMorphInteractionMixin.java'
        }
    }
}

loom {
    mixin {
        defaultRefmapName = "identity2-common-refmap.json"
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modCompileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modImplementation "curse.maven:gabous-libs-1367332:8280105"
    modImplementation "curse.maven:naturalist-627986:6863943"
    modImplementation "curse.maven:geckolib-388172:7553267"
    modImplementation "curse.maven:alexs-mobs-426558:5698791"
    modCompileOnly "curse.maven:alexs-caves-924854:5848216"
    modImplementation "curse.maven:citadel-331936:7476570"
    compileOnly "io.github.llamalad7:mixinextras-common:0.3.2"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.2"
}
architectury {
    common("fabric", "neoforge")
}

configurations {
    dev
}

artifacts {
    dev(jar)
}
