sourceSets {
    main {
        java {
            exclude 'net/Gabou/identity2/mixin/PlayerMorphInteractionMixin.java'
        }
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modCompileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modImplementation "curse.maven:gabous-libs-1367332:7701613"
}
architectury {
    common("fabric", "forge","neoforge")
}

configurations {
    dev
}

artifacts {
    dev(jar)
}
allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    archivesBaseName = rootProject.archives_name
    version = rootProject.mod_version + "-" + rootProject.minecraft_version
    group = rootProject.maven_group

    repositories {
        maven { url = 'https://maven.architectury.dev' }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 17
    }

    java {
        withSourcesJar()
    }
}
