modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "identity2"
version = "${version}"
displayName = "Identity2"
authors = "Gabou"
description = '''

'''
#logoFile = ""

[[dependencies.identity2]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.identity2]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.identity2]]
modId = "gaboulibs"
type = "required"
versionRange = "[1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "identity2.mixins.json"

[[mixins]]
config = "identity2.client.mixins.json"
